import { Link, useParams } from "react-router";
import { ArrowRight, BookOpen, CheckCircle2, PenLine, AlertCircle } from "lucide-react";
import { useProjectOverview, useChapters, useStory } from "../../entities/project/queries";
import { BookCover, bookStatus } from "../../shared/ui/book-cover";
import { ErrorNote } from "../../shared/ui";
import { QuoteCard } from "../library/library-page";
export function DashboardPage(){
 const {projectId=""}=useParams();const query=useProjectOverview(projectId);const chapters=useChapters(projectId);const story=useStory(projectId);
 if(query.isPending)return <div className="cf-page" role="status">正在打开作品…</div>;
 if(query.isError)return <div className="cf-page"><ErrorNote error={query.error}/></div>;
 const data=query.data;const p=data.project;const current=data.currentChapter;const link=`/books/${projectId}/write${current?.documentId?`/${current.documentId}`:""}`;const progress=data.progress;const ratio=progress.totalChapters?Math.round(progress.committedChapters/progress.totalChapters*100):0;
 return <div className="cf-page"><div className="cf-page-title"><div><h1>创作首页</h1><p>回到你的故事，继续推进今天的创作。</p></div></div><div className="cf-content-aside"><div><section className="cf-card cf-dashboard-hero"><BookCover project={p}/><div><h2>{p.title}</h2><span className="cf-badge">{bookStatus(p.phase)}</span><p>{progress.wordCount.toLocaleString()} 字 · {progress.totalChapters} 章节</p><p>{p.premise||"让每一个故事，都被认真对待。"}</p></div><div className="cf-continue"><small>接着上次，继续写</small><h3>{current?.title??"故事的第一章"}</h3><p>{data.activeTask?"有创作任务正在处理，可在任务中心查看。":"一章一章，让想象成为文字。"}</p><Link className="cf-primary" to={link}><PenLine size={18}/>继续写作</Link><Link className="cf-text-link" to={`/books/${projectId}/outline`}>查看大纲 <ArrowRight size={14}/></Link></div></section>
 <h2>下一步建议</h2><div className="cf-suggestion-grid"><Link className="cf-card" to={link}><CheckCircle2/><strong>{current?"本章已准备好":"开启第一章"}</strong><p>{current?.title??"先写下来，故事会慢慢展开。"}</p></Link><Link className="cf-card" to={link+"?tab=review"}><AlertCircle/><strong>{data.pending.reviewIssues?`${data.pending.reviewIssues} 个问题待检查`:"让故事前后一致"}</strong><p>{data.pending.reviewIssues?"查看本章检查与修改建议":"写完一章后，检查人物与剧情。"}</p></Link><Link className="cf-card" to={`/books/${projectId}/outline`}><BookOpen/><strong>梳理接下来的故事</strong><p>提前准备章纲，让创作更从容。</p></Link></div>
 <div className="cf-section-title"><h2>最近章节</h2><Link className="cf-text-link" to={`/books/${projectId}/write`}>查看全部 →</Link></div><section className="cf-card">{(chapters.data??[]).slice().sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).slice(0,5).map(ch=><div className="cf-chapter-row" key={ch.id}><BookOpen size={18}/><div><strong>{ch.title}</strong><small>{ch.currentVersionId?"已有保存版本":"草稿"} · {new Date(ch.updatedAt).toLocaleDateString("zh-CN")}</small></div><Link className="cf-button" to={`/books/${projectId}/write/${ch.id}`}>继续</Link></div>)}{!chapters.data?.length?<p>还没有章节。点击「继续写作」开始第一章。</p>:null}</section>
 <section className="cf-card cf-progress-card"><h2>作品进度</h2><strong>{progress.committedChapters} / {progress.totalChapters} 章已定稿</strong><progress max={100} value={ratio}/><small>{ratio}%</small></section></div><aside className="cf-side-stack"><section className="cf-card"><h2>待处理</h2>{[["章节检查",data.pending.reviewIssues],["AI 改写建议",data.pending.revisionProposals],["设定变化",data.pending.canonChangeSets]].map(([label,value])=><div className="cf-stat" key={label}><strong>{label}</strong><b>{value}</b></div>)}</section><section className="cf-card"><h2>伏笔提醒</h2>{story.data?.foreshadows.slice(0,4).map(f=><div className="cf-chapter-row" key={f.id}><span className="cf-dot"/><strong>{f.title}</strong></div>)}{!story.data?.foreshadows.length?<p>埋下的伏笔，会在这里等待回响。</p>:null}<Link className="cf-text-link" to={`/books/${projectId}/knowledge/foreshadow`}>查看作品设定 →</Link></section><QuoteCard/></aside></div></div>;
}
