import { mkdirSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

import { buildViewSpec } from "../runtime/view-spec.mjs";

export function renderView(root, type, options = {}) {
  const spec = buildViewSpec(root, type, options);
  const outputDir = resolve(root, options.outputDir ?? "outputs");
  mkdirSync(outputDir, { recursive: true });
  const stamp = new Date().toISOString().replace(/[:.]/gu, "-");
  const path = join(outputDir, `${type}-${stamp}.html`);
  writeFileSync(path, htmlDocument(spec), "utf8");
  return { type, title: spec.title, path, spec };
}

function htmlDocument(spec) {
  const data = JSON.stringify(spec).replace(/</gu, "\\u003c");
  return `<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>${escapeHtml(spec.title ?? "ChapterFlow View")}</title>
<style>
:root{color-scheme:light dark;font-family:Inter,"PingFang SC","Microsoft YaHei",system-ui,sans-serif;--bg:#f6f7f9;--card:#fff;--text:#172033;--muted:#697386;--line:#dce1e8;--accent:#335eea;--soft:#eef2ff;--good:#217a4b;--warn:#9a5b00;--danger:#b42318} @media(prefers-color-scheme:dark){:root{--bg:#11151d;--card:#181e29;--text:#edf2f7;--muted:#9ca8ba;--line:#303949;--accent:#8aa4ff;--soft:#202a43;--good:#69d39a;--warn:#f2bd62;--danger:#ff8c82}}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text)}main{max-width:1180px;margin:0 auto;padding:28px 20px 56px}header{display:flex;align-items:flex-end;justify-content:space-between;gap:16px;margin-bottom:20px}h1{font-size:26px;margin:0}h2,h3{margin:0}.sub{color:var(--muted);font-size:13px}.card{background:var(--card);border:1px solid var(--line);border-radius:16px;padding:18px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:14px}.pill{display:inline-flex;padding:3px 8px;border-radius:999px;background:var(--soft);font-size:12px}.muted{color:var(--muted)}button{border:1px solid var(--line);background:var(--card);color:var(--text);border-radius:10px;padding:8px 11px;cursor:pointer}.timeline{position:relative;padding-left:22px}.timeline:before{content:"";position:absolute;left:6px;top:8px;bottom:8px;width:2px;background:var(--line)}.event{position:relative;margin-bottom:14px}.event:before{content:"";position:absolute;left:-20px;top:8px;width:10px;height:10px;border-radius:50%;background:var(--accent)}.event small{color:var(--muted)}.promise{display:grid;grid-template-columns:minmax(150px,1.3fr) 2.7fr;gap:12px;align-items:center;padding:12px 0;border-bottom:1px solid var(--line)}.track{display:flex;align-items:center;gap:6px;min-height:34px;overflow-x:auto}.mark{white-space:nowrap;border-radius:999px;padding:5px 8px;background:var(--soft);font-size:12px}.mark[data-action="PAYOFF"]{color:var(--good)}.mark[data-action="OPEN"]{color:var(--accent)}.foreshadow{display:grid;grid-template-columns:minmax(150px,1fr) 3fr;gap:14px;padding:12px 0;border-bottom:1px solid var(--line)}.milestones{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.milestone{padding:7px 10px;border-radius:10px;background:var(--soft);font-size:12px}.chapter{border-left:4px solid var(--line)}.chapter[data-written="true"]{border-left-color:var(--good)}.chapter .meta{display:flex;gap:7px;flex-wrap:wrap;margin-top:8px}.risk{border-left:3px solid var(--warn);padding-left:10px;margin-top:9px}.metrics{display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));gap:8px;margin-top:12px}.metric{background:var(--soft);border-radius:10px;padding:10px}.metric strong{display:block;font-size:18px}.graph-wrap{display:grid;grid-template-columns:minmax(0,2.3fr) minmax(220px,1fr);gap:14px}.graph{width:100%;min-height:580px;background:var(--card);border:1px solid var(--line);border-radius:16px}.edge{stroke:var(--line);stroke-width:2}.edge-label{font-size:11px;fill:var(--muted)}.node{cursor:pointer}.node circle{fill:var(--soft);stroke:var(--accent);stroke-width:2}.node text{font-size:12px;fill:var(--text);text-anchor:middle}.details p{white-space:pre-wrap}.empty{padding:36px;text-align:center;color:var(--muted)}@media(max-width:720px){main{padding:18px 12px 40px}.graph-wrap{grid-template-columns:1fr}.graph{min-height:420px}.promise,.foreshadow{grid-template-columns:1fr}}
</style>
</head>
<body><main><header><div><div class="sub">ChapterFlow Skill Kit · Snapshot View</div><h1 id="title"></h1></div><div class="sub" id="meta"></div></header><div id="app"></div></main>
<script>
const spec=${data};
const app=document.getElementById('app');document.getElementById('title').textContent=spec.title||'ChapterFlow View';document.getElementById('meta').textContent=new Date().toLocaleString('zh-CN');
const esc=(v)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function empty(text){app.innerHTML='<div class="card empty">'+esc(text)+'</div>'}
function render(){switch(spec.type){case'character_graph':return graph();case'timeline':return timeline();case'promise_board':return promises();case'foreshadow_map':return foreshadows();case'story_map':return story();case'chapter_health':return health();default:return empty('暂不支持这个视图')}}
function graph(){if(!spec.nodes?.length)return empty('还没有人物或实体数据。');const w=760,h=560,cx=w/2,cy=h/2,r=Math.min(w,h)*.36;const positions=new Map(spec.nodes.map((n,i)=>[n.id,{x:cx+Math.cos((Math.PI*2*i/spec.nodes.length)-Math.PI/2)*r,y:cy+Math.sin((Math.PI*2*i/spec.nodes.length)-Math.PI/2)*r}]));let svg='<svg class="graph" viewBox="0 0 '+w+' '+h+'" role="img" aria-label="人物关系图">';for(const e of spec.edges||[]){const a=positions.get(e.source),b=positions.get(e.target);if(!a||!b)continue;svg+='<line class="edge" x1="'+a.x+'" y1="'+a.y+'" x2="'+b.x+'" y2="'+b.y+'"/><text class="edge-label" x="'+((a.x+b.x)/2)+'" y="'+((a.y+b.y)/2-5)+'">'+esc(e.label)+'</text>'}for(const n of spec.nodes){const p=positions.get(n.id);svg+='<g class="node" tabindex="0" data-id="'+esc(n.id)+'" transform="translate('+p.x+' '+p.y+')"><circle r="34"/><text y="4">'+esc(n.label.slice(0,8))+'</text></g>'}svg+='</svg>';app.innerHTML='<div class="graph-wrap">'+svg+'<aside class="card details"><h3>选择一个人物</h3><p class="muted">点击节点查看人物说明和当前关系。</p></aside></div>';const details=app.querySelector('.details');app.querySelectorAll('.node').forEach(node=>{const show=()=>{const item=spec.nodes.find(n=>n.id===node.dataset.id);const rels=(spec.edges||[]).filter(e=>e.source===item.id||e.target===item.id);details.innerHTML='<h3>'+esc(item.label)+'</h3><p>'+esc(item.summary||'暂无人物说明')+'</p><div class="sub">'+esc(item.group||'entity')+'</div><hr><strong>当前关系</strong>'+(rels.length?rels.map(r=>'<p>· '+esc(r.label)+(r.notes?' — '+esc(r.notes):'')+'</p>').join(''):'<p class="muted">暂无关系</p>')};node.addEventListener('click',show);node.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();show()}})})}
function timeline(){if(!spec.events?.length)return empty('还没有故事时间线事件。');app.innerHTML='<section class="card timeline">'+spec.events.map(e=>'<article class="event"><small>'+esc(e.storyTime||('第 '+(e.chapterIndex??'?')+' 章'))+'</small><h3>'+esc(e.title)+'</h3><p>'+esc(e.summary||'')+'</p>'+(e.chapterIndex?'<span class="pill">第 '+e.chapterIndex+' 章</span>':'')+'</article>').join('')+'</section>'}
function promises(){if(!spec.promises?.length)return empty('还没有记录 Reader Promise。');app.innerHTML='<section class="card">'+spec.promises.map(p=>'<div class="promise"><div><strong>'+esc(p.title)+'</strong><div class="sub">'+esc(p.status)+(p.targetChapter?' · 目标第 '+p.targetChapter+' 章':'')+'</div></div><div class="track">'+p.events.map(e=>'<span class="mark" data-action="'+esc(e.action)+'">'+esc(e.action)+' · '+e.chapterIndex+'</span>').join('<span>→</span>')+'</div></div>').join('')+'</section>'}
function foreshadows(){if(!spec.foreshadows?.length)return empty('还没有记录伏笔。');app.innerHTML='<section class="card">'+spec.foreshadows.map(f=>'<div class="foreshadow"><div><strong>'+esc(f.title)+'</strong><div class="sub">'+esc(f.status)+'</div></div><div class="milestones">'+(f.introducedChapter?'<span class="milestone">埋下 · '+f.introducedChapter+'</span>':'')+(f.targetChapter?'<span>→</span><span class="milestone">计划回收 · '+f.targetChapter+'</span>':'')+(f.resolvedChapter?'<span>→</span><span class="milestone">实际回收 · '+f.resolvedChapter+'</span>':'')+'</div></div>').join('')+'</section>'}
function story(){const intro=spec.arc?'<section class="card" style="margin-bottom:14px"><h3>'+esc(spec.arc.title)+'</h3><p>'+esc(spec.arc.goal||'')+'</p><div class="meta"><span class="pill">冲突 '+esc(spec.arc.conflict||'未填')+'</span><span class="pill">阶段回收 '+esc(spec.arc.payoff||'未填')+'</span></div></section>':'';if(!spec.chapters?.length){app.innerHTML=intro;return}app.innerHTML=intro+'<div class="grid">'+spec.chapters.map(c=>'<article class="card chapter" data-written="'+Boolean(c.written)+'"><div class="sub">第 '+esc(c.index)+' 章 · '+(c.written?'已有正文':'规划中')+'</div><h3>'+esc(c.title||'未命名章节')+'</h3><p>'+esc(c.conflict||'')+'</p><div class="meta">'+(c.purpose?'<span class="pill">'+esc(c.purpose)+'</span>':'')+(c.emotionTarget?'<span class="pill">'+esc(c.emotionTarget)+'</span>':'')+'</div>'+(c.readerExpectation?'<p><strong>期待：</strong>'+esc(c.readerExpectation)+'</p>':'')+(c.hook?'<p><strong>章尾：</strong>'+esc(c.hook)+'</p>':'')+(c.payoff?'<p><strong>兑现：</strong>'+esc(c.payoff)+'</p>':'')+'</article>').join('')+'</div>'}
function health(){if(!spec.chapters?.length)return empty('还没有可检查的前三章正文。');app.innerHTML='<div class="grid">'+spec.chapters.map(c=>'<article class="card"><div class="sub">第 '+c.index+' 章</div><h3>'+esc(c.title)+'</h3><div class="metrics"><div class="metric"><span>正文字符</span><strong>'+c.metrics.characterCount+'</strong></div><div class="metric"><span>对话占比</span><strong>'+Math.round(c.metrics.dialogueRatio*100)+'%</strong></div><div class="metric"><span>解释段</span><strong>'+c.metrics.expositionRunCount+'</strong></div><div class="metric"><span>重复段</span><strong>'+c.metrics.repeatedParagraphCount+'</strong></div></div>'+(c.risks.length?c.risks.map(r=>'<div class="risk"><strong>'+esc(r.label)+'</strong><div class="sub">'+esc(r.locations.join('、')||'全文观察')+'</div><p>'+esc(r.explanation)+'</p></div>').join(''):'<p class="muted">确定性信号暂未发现需要重点回看的项目。</p>')+'</article>').join('')+'</div><p class="sub" style="margin-top:12px">'+esc(spec.note||'')+'</p>'}
render();
</script></body></html>`;
}

function escapeHtml(value) {
  return String(value ?? "").replace(/[&<>"']/gu, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char]);
}
