/** Shared cache identities. Keep legacy keys stable during incremental migration. */
export const queryKeys = {
  projects: ["projects"] as const,
  recycleBin: ["projects", "recycle-bin"] as const,
  health: ["health"] as const,
  project: (id: string | null) => ["project", id] as const,
  overview: (id: string | null) => ["project", id, "overview"] as const,
  story: (id: string | null) => ["project", id, "bible"] as const,
  entities: (id: string | null) => ["project", id, "canon", "entities"] as const,
  facts: (id: string | null) => ["project", id, "canon", "facts"] as const,
  relationships: (id: string | null) => ["project", id, "canon", "relationships"] as const,
  relationshipHistory: (id: string | null) => ["project", id, "canon", "relationships", "history"] as const,
  timeline: (id: string | null) => ["project", id, "canon", "timeline"] as const,
  foreshadows: (id: string | null) => ["project", id, "canon", "foreshadows"] as const,
  storyEvidence: (id: string | null) => ["project", id, "story-evidence"] as const,
  outlineRemovalImpact: (projectId: string | null, nodeId: string | null) =>
    ["project", projectId, "outline", nodeId, "removal-impact"] as const,
  documents: (id: string | null, includeArchived = false) =>
    ["project", id, "studio", "documents", ...(includeArchived ? ["archived"] : [])] as const,
  document: (id: string | null, documentId: string | null) =>
    ["project", id, "studio", "document", documentId] as const,
  runs: (id: string | null) => ["project", id, "runs"] as const,
  review: (id: string | null) => ["project", id, "review"] as const,
  run: (id: string | null) => ["run", id] as const,
  bookProfile: (id: string | null) => ["chapterflow", "book-profile", id] as const,
  bookProfileHistory: (id: string | null) => ["chapterflow", "book-profile-history", id] as const,
  creativePresets: (id: string | null) => ["chapterflow", "creative-presets", id] as const,
  creativePresetHistory: (presetId: string | null) =>
    ["chapterflow", "creative-preset-history", presetId] as const,
  chapterBrief: (projectId: string | null, outlineNodeId: string | null) =>
    ["chapterflow", "chapter-brief", projectId, outlineNodeId] as const,
  chapterBriefHistory: (projectId: string | null, outlineNodeId: string | null) =>
    ["chapterflow", "chapter-brief-history", projectId, outlineNodeId] as const,
  webNovelCandidates: (projectId: string | null, kind: string | null, outlineNodeId: string | null = null) =>
    ["chapterflow", "web-novel-candidates", projectId, kind, outlineNodeId] as const,
  platformMetrics: (id: string | null) => ["chapterflow", "platform-metrics", id] as const,
  platformMetricImports: (id: string | null) => ["chapterflow", "platform-metric-imports", id] as const,
  platformMetricReport: (id: string | null) => ["chapterflow", "platform-metric-report", id] as const,
  publishRecords: (id: string | null) => ["chapterflow", "publish-records", id] as const,
  exportBatches: (id: string | null) => ["chapterflow", "export-batches", id] as const,
  quality: (id: string | null) => ["project", id, "quality"] as const,
  projectBackups: (id: string | null) => ["project", id, "backups"] as const,
  styles: (id: string | null) => ["project", id, "styles"] as const,
  writingSkills: (id: string | null) => ["project", id, "writing-skills"] as const,
  agentSkills: (id: string | null) => ["project", id, "agent-skills"] as const,
  imports: (id: string | null) => ["project", id, "imports"] as const,
  importBatch: (id: string | null) => ["import", id] as const,
  canonChangeSets: (id: string | null) => ["project", id, "canon-change-sets"] as const,
  canonCandidates: (id: string | null, spread: string | null) =>
    ["project", id, "canon-candidates", spread] as const,
  compass: (id: string | null) => ["project", id, "compass"] as const,
  foundation: (id: string | null) => ["chapterflow", "foundation", id] as const,
  predictions: (id: string | null) => ["chapterflow", "predictions", id] as const,
  memories: (id: string | null) => ["chapterflow", "memories", id] as const,
  templates: ["chapterflow", "templates"] as const,
  systemBackups: ["system-backups"] as const,
  archivedProjects: ["projects", "archived"] as const,
  assistantConversations: (id: string | null) => ["assistant", id, "conversations"] as const,
  assistantConversation: (projectId: string | null, conversationId: string | null) => ["assistant", projectId, "conversation", conversationId] as const,
  assistantModels: ["assistant-models", "models"] as const,
  assistantProviders: ["assistant-models", "providers"] as const,
  assistantAssignments: ["assistant-models", "assignments"] as const,
  autopilotSessions: (id: string | null) => ["chapterflow", "quick-create", id, "sessions"] as const,
  autopilotSession: (id: string | null) => ["chapterflow", "quick-create", "session", id] as const,
  qualityReports: (id: string | null) => ["chapterflow", "quality", id] as const,
  openingCheckHistory: (id: string | null) => ["chapterflow", "opening-check-history", id] as const,
  openingCheckAudit: (id: string | null) => ["chapterflow", "opening-check-audit", id] as const,
};
